name: 编译备忘录应用APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v4

      - name: 设置JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: 设置Android SDK
        uses: android-actions/setup-android@v3
        with:
          android-sdk-version: '33'
          packages: |
            platform-tools
            build-tools;33.0.2
            platforms;android-33

      - name: 授权Gradle脚本
        run: chmod +x ./gradlew

      - name: 构建debug APK
        run: ./gradlew assembleDebug

      - name: 上传APK文件
        uses: actions/upload-artifact@v3
        with:
          name: memo-app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
