name: 编译备忘录应用APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v4

      - name: 设置JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: 设置Android SDK
        # 使用已发布的稳定版本v3
        uses: android-actions/setup-android@v3
        with:
          # 明确指定cmdline-tools版本（v3兼容的稳定版本）
          cmdline-tools-version: 9.0
          packages: |
            platform-tools
            build-tools;33.0.2  # 稳定版本，兼容性好
            platforms;android-33  # 与构建工具版本匹配
            cmdline-tools;9.0  # 明确版本号，避免latest带来的问题

      - name: 接受Android SDK许可证
        run: |
          yes | $ANDROID_HOME/cmdline-tools/9.0/bin/sdkmanager --licenses > /dev/null 2>&1

      - name: 授权Gradle脚本
        run: chmod +x ./gradlew

      - name: 构建debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: 上传APK文件
        uses: actions/upload-artifact@v4
        with:
          name: memo-app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
